robotology/robometry

- .github/workflows/ci.yml
This PR adds continuous integration for `windows`, `macOs`, and `ubuntu`, with both `Release` and `Debug` (we may trim away one of them.
The ci installs as deps:
- `ycm`
- `yarp`
- `matio-cpp`
It fixes #3 
Please review code
> Add Continous integration

- src/examples/CMakeLists.txt
- src/examples/matio_matrix_example.cpp
- src/examples/matio_timeseries_example.cpp
- src/examples/matio_vector_example.cpp
This pull-request introduces 2 simple examples of matioCpp use (for vectors and matrices), and an example implementation of the structure for saving timeseries in `.mat` files.
This fixes #4 and fixes #8 .
> Add matioCpp examples

- .github/workflows/ci.yml
- src/examples/CMakeLists.txt
- src/examples/circular_buffer_record_example.cpp
- src/examples/telemetry_buffer_example.cpp
- src/libYARP_telemetry/src/CMakeLists.txt
- src/libYARP_telemetry/src/yarp/telemetry/Buffer.h
I wrote down a first draft of the `yarp::telemetry::Buffer` API.
It is a template class that contains a `boost::circular_buffer<yarp::telemetry::Record<T>>`, a `std::string` that defines the name of the variable to be dumped, and a `vector<size_t>` defining the dimensionality of `T`.
I took inspiration from https://github.com/dic-iit/matio-cpp/blob/master/include/matioCpp/MultiDimensionalArray.h since the next step will be to use `matio-cpp` in order to dump the data.
I wrote also some utility functions, I have no idea if they can be useful or we need other functions I didn't add.
It fixes #6
> First draft of Buffer API

- CMakeLists.txt
- src/examples/CB_to_matfile_example.cpp
- src/examples/CMakeLists.txt
After working with Nicolo in the morning, we came up with a small example of the full pipeline, from a data vector to circular buffer, then reading from the circular buffer and creating a mat file with matioCpp.
The reading is done in a thread, made safe by use of mutex locks. The data is stored in a local collection, and the mat file is created at the end of the run (when the user chooses to terminate the module).
This already uses the Buffer API developed by @Nicogene
> Pipeline example

- src/examples/CB_to_matfile_example.cpp
- src/examples/CMakeLists.txt
- src/examples/circular_buffer_record_example.cpp
- src/examples/telemetry_buffer_example.cpp
- src/examples/telemetry_buffer_manager_example.cpp
- src/libYARP_telemetry/src/CMakeLists.txt
- src/libYARP_telemetry/src/yarp/telemetry/Buffer.h
- src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
- src/libYARP_telemetry/src/yarp/telemetry/Record.h
It fixes #29 
It fixes #23
This PR introduces these changes:
- Use `double` as timestamp in `Record<T>` (see https://github.com/robotology-playground/yarp-telemetry/issues/28#issuecomment-758003434)
- Use `std::vector<T>` as type for `m_datum` of `Record<T>`(see https://github.com/robotology-playground/yarp-telemetry/issues/23#issuecomment-756782927).
- Implements https://github.com/robotology-playground/yarp-telemetry/pull/27#issuecomment-758001061
- Add `BufferManager` class
This is a template class that contains a `std::map<string, telemetry::Buffer<T>>` that contains all the user-defined `Buffer`s, each one associated to a variable.
Each `BufferManager` defines a .mat structure containing all the variables.
For now it DOES NOT handle the multithreading.
Here is the example of scalar …
> Add BufferManager API

- src/examples/telemetry_buffer_manager_example.cpp
- src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
- src/libYARP_telemetry/src/yarp/telemetry/Record.h
As we discussed in the last meeting we decided to implement the auto-save option in order to save the `.mat` file in the destructor.
The option is **false by default** but this can be changed.
Moreover, I also changed the example that uses the `BufferManager` in order to exploit this autosave option.
It fixes #35 
Please review code.
> BufferManager: add auto save option

- src/libYARP_telemetry/src/CMakeLists.txt
Since the `YARP_telemetry_PUBLIC_DEPS` was not correctly set, it was possible to consume this library without linking `matio-cpp` library, triggering a linking issue (#44)
Please review code.
> Cmake: fix public deps of YARP_telemetry

- README.md
- src/examples/telemetry_buffer_manager_example.cpp
- src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
After an analysis on who `matio-cpp` works with @AlexAntn we discovered that the first two dimensions have to represent the single sample, and the one regarding the number of samples is to be the last one in the list.
It fixes #45 
Moreover, we added an example using matrix variables(2x3 and 3x2)
cc @S-Dafarra
> BufferManager: fix order dimensions field

- README.md
- src/examples/telemetry_buffer_manager_example.cpp
- src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
This PR adds some configuration methods, now you are no more forced to configure the BufferManager at the construction phase.
The examples have been cleaned up and refactored accordingly.
Please review code.
cc @S-Dafarra
> BufferManager: add configuration methods and examples enhancement

- src/examples/CB_to_matfile_example.cpp
- src/examples/CMakeLists.txt
- src/examples/circular_buffer_record_example.cpp
- src/examples/telemetry_buffer_periodic_save.cpp
- src/libYARP_telemetry/src/CMakeLists.txt
- src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
This PR introduces a periodic saving method to the BufferManager API. 
It runs in a thread that is activated periodically, checking the buffer to see if the amount of data currently stored crosses a specified threshold. If the threshold is crossed, the data is saved to a file, and the buffer is cleared and ready to accept more data.
This is a first step towards ensuring no data loss since we are now not bound by the size of the buffer. The file names are incremented at each save (so, e.g.: `buffer_test_0.mat`, `buffer_test_1.mat`, etc). 
The saving of the file is triggered if any channel crosses the data amount threshold. This ensures that the same .mat file corresponds to the same time-window, even if the number of entries between the channels doesn't match (e.g.: if the channels have …
> BufferManager: added a periodic saving method and updated examples

- CMakeLists.txt
- src/examples/CMakeLists.txt
- src/examples/conf/test_json.json
- src/examples/telemetry_buffer_manager_conf_file.cpp
- src/examples/telemetry_buffer_manager_example.cpp
- src/examples/telemetry_buffer_periodic_save.cpp
- src/libYARP_telemetry/src/CMakeLists.txt
- src/libYARP_telemetry/src/yarp/telemetry/Buffer.h
- src/libYARP_telemetry/src/yarp/telemetry/BufferConfig.cpp
- src/libYARP_telemetry/src/yarp/telemetry/BufferConfig.h
- src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
- The `ChannelInfo` has been changed from a struct of two elements to a
`std::pair`, in order to be easily handled with the JSON file conf.
- All the flags, options of the BufferManager have been put in the BufferConfig
- The empty constructor is allowed now, for this we added all the functions
needed for configuring a default BufferManager(It fixes #60)
- The mutex has been added in `saveToFile`(partially address #9)
- Now the periodicSave, saves only the variables that go above the
data_treshold specified
- Fixes the bug of not saving when the threshold > n_samples(fixes #61 )
- It has been added the configuration from JSON file using [this library](https://github.com/nlohmann/json) with relative example (it fixes #39) 
- It add the possibility to save `BufferConfig` to json file(it …
> BufferManager: add mutex, configuration from file, empty constructor workflow et al

- .github/workflows/ci.yml
- CMakeLists.txt
- src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
- test/CMakeLists.txt
This PR adds Valgrind to the unit tests and examples that run in the CI(for the Ubuntu part).
It fixes #79 
It fixes #64 
Please review code
(MERGE AFTER #78 )
> Add valgrind to the CI

- CMakeLists.txt
- src/CMakeLists.txt
- src/telemetryDeviceDumper/CMakeLists.txt
- src/telemetryDeviceDumper/TelemetryDeviceDumper.cpp
- src/telemetryDeviceDumper/TelemetryDeviceDumper.h
This addresses #15 
I made it `IWrapper`/`IMultipleWrapper` but we can discuss the use cases (cc @AlexAntn @S-Dafarra @traversaro )
@AlexAntn and I implemented the first working version
For now it dumps the encoders, the encoders' speed and accelerations for the specified parts of the specified robot.
Here is an example of usage:
```bash
$ yarpdev --device telemetryDeviceDumper --parts "(head left_arm right_leg)"
```
(if not specified `icubSim` is the default value for `robot`)
And here are the file produced:
```
-a----          3/1/2021   3:20 PM          55696 telemetryDeviceDumper_icubSim_head_1614608427.576625.mat
-a----          3/1/2021   3:20 PM          62584 telemetryDeviceDumper_icubSim_head_1614608431.579932.mat
-a----          3/1/2021   3:20 PM          62592 …
```
> telemetryDeviceDumper: add first draft

- README.md
- src/examples/conf/test_json.json
- src/libYARP_telemetry/src/yarp/telemetry/BufferConfig.cpp
- src/libYARP_telemetry/src/yarp/telemetry/BufferConfig.h
- src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
- test/BufferManagerTest.cpp
It is now possible to specify a custom path(`path`) and a list of string(`description_list`) for describing the data logged.
```
>> buffer_manager_test_conf_file = 
struct with fields:
description_list: {2×1 cell}
one: [1×1 struct]
two: [1×1 struct]
>> buffer_manager_test_conf_file.description_list
ans =
2×1 cell array
{'This is a test'}
{'Or it isn't?'  }
```
It fixes #86 
It fixes #88
> Add description list and path to the BufferManager configuration

- src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
- src/libYARP_telemetry/src/yarp/telemetry/Record.h
- test/BufferManagerTest.cpp
If you first add the channels and then configure the BM (with or without file) the size of the buffers was not updated.
Moreover, I had to add the default constructor of `Record` for resizing, I don't know why the "rule of zero" is violated.
> Fix BufferManager configuration

- src/telemetryDeviceDumper/CMakeLists.txt
- src/telemetryDeviceDumper/TelemetryDeviceDumper.cpp
- src/telemetryDeviceDumper/TelemetryDeviceDumper.h
- src/telemetryDeviceDumper/app/telelmetryDeviceDumper.xml
It fixes #85 
It has to be tested and it misses some API features of the library for work correctly
(see #86 and #88 )
It has to be merged after #84 
cc @AlexAntn @traversaro @S-Dafarra @drdanz
>  telemetryDeviceDumper: first draft attaching multiple controlboards and use the remapper

- src/telemetryDeviceDumper/TelemetryDeviceDumper.cpp
Fix the log of acceleration, it was a copy-past error.
See https://github.com/robotology-playground/yarp-telemetry/issues/87#issuecomment-800941099
> telemetryDeviceDumper: fix acceleration log

- src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
- test/BufferManagerTest.cpp
This is used for handling the save thread and this should avoid awaiting
the thread save_period seconds to wake up in the closure phase.
It fixes #94
cc @S-Dafarra @lornat75
> BufferManager: introduce the usage of the condition variable

- src/libYARP_telemetry/src/yarp/telemetry/Buffer.h
- src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
It introduces the `BufferInfo` struct that holds the Buffer, the dimensions, and the mutex of the respective buffer. The push_back now lock the mutex of the buffer we are writing to it, keeping the others free.
It fixes #9 
cc @S-Dafarra
> BufferManager: fix multithreading push_back

- README.md
- src/telemetryDeviceDumper/TelemetryDeviceDumper.cpp
- src/telemetryDeviceDumper/TelemetryDeviceDumper.h
- src/telemetryDeviceDumper/app/telelmetryDeviceDumper.xml
It fixes #100
Before proceeding with #101, I would settle which parameters are configurable from the file and which ones are mandatory.
In this implementation, the configuration of the BM from JSON will overwrite the parameter-by-parameters configuration.
`n_samples` is mandatory, as it is mandatory also `save_period` if `save_periodically` is set to true.
At the end it checks, if both `save_periodically` and `auto_save` are set to false the configuration will fail and the device will close.
An issue that I see is that the configuration with the JSON and the configuration parameter-by-parameter are different.
`experiment_name` is `file_name` in the JSON configuration(this probably has to be fixed) and in the JSON configuration ALL the parameters are mandatory for …
> TelemetryDeviceDumper: make the BM configurable from xml file

- CMakeLists.txt
- src/libYARP_telemetry/src/yarp/telemetry/Buffer.h
- src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
- test/BufferManagerTest.cpp
BufferManager used to call `resize()` on the Buffers, I thought that it changed only `capacity()` and size() was changed only when `push_back` was invoked.
I changed the `resize()` call in `configure` to `set_capacity`
I tested this patch running `telemetryDeviceDumper` with the gazebo simulator.
It fixes #110 
cc @S-Dafarra
> Fix BufferManager buffer allocation in the configuration phase

- CMakeLists.txt
- test/BufferManagerTest.cpp
- test/CMakeLists.txt
Added the benchmarking section in `BufferManagerTest`.
It can be enable with `ENABLE_BENCHMARKING` cmake option.
TODO: remove https://github.com/robotology/yarp-telemetry/pull/121/commits/41e53d06239735337c338c22209a68539f9541c1 before merging, it has been added because the messages printed ruin the format of the benchmarking
It fixes #116 
cc @S-Dafarra @drdanz
> Tests: add benchmarking for integers

- .github/workflows/conda-ci.yml
To fix https://github.com/robotology/yarp-telemetry/issues/80 , it was easier to me to just add a new conda-based CI as the configuration of environment on Conda on Windows is much easier.
> Add conda-based CI configuration

- CHANGELOG.md
- src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferManager.h
After a discussion with @prashanthr05, we realized that sometimes it is important to store data in different channels but with the same timestamp. 
In principle, this would be possible by storing structs of data for example, but this is not currently supported. An easy workaround is to store all the data in separated vectors. On the other hand, to make sure that all the data is saved in a synchronized way, it is necessary to specify also the timestamp.
This may also be helpful when storing the data read from the yarp interfaces, saving the timestamp retrieved by the ``yarp`` interface, rather than the one obtained by the application.
> Added possibility to explicitly set the timestamp of a Record with push_back

- CHANGELOG.md
- CMakeLists.txt
- README.md
- src/examples/conf/test_json.json
- src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferConfig.cpp
- src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferConfig.h
- src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferManager.h
- test/BufferManagerTest.cpp
This requires `matioCpp v0.1.1`.
To be merged after #121 
It fixes #115
> BufferManager: add zlib compression

- CHANGELOG.md
- README.md
- src/telemetryDeviceDumper/TelemetryDeviceDumper.cpp
- src/telemetryDeviceDumper/TelemetryDeviceDumper.h
It fixes #113
There are still open points, for now it simply dump everythin, we should define how to
group these quantities under options.
TODO
> telemetryDeviceDumper: added all the controlBoardDumper interfaces

- src/libYARP_telemetry/src/yarp/telemetry/experimental/api.h
I realized that the `YARP_DEPRECATED_API` definition is broken, and won't work anyway outside `YARP_os`
AFAIK, this is the only place outside YARP where this definition is used, therefore I'm planning to change this to a proper `EXPORT`/`IMPORT` definition in YARP master, and I'm not sure if it is possible to do this ensuring the compatibility, without breaking the API.
This means that current definition will work with YARP 3.4 only, and the new definition will require YARP master which is unreleased yet.
Therefore I suggest to remove these 2 lines (I don't think there is any deprecated API in yarp_telemetry yet), and to wait until YARP 3.5 is released to depend on YARP 3.5 and fix the definition.
> Remove YARP_telemetry_DEPRECATED_API definition

- src/libYARP_telemetry/src/CMakeLists.txt
- src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferManager.h
Fix https://github.com/robotology/robotology-superbuild/issues/731 . 
As discussed in https://github.com/robotology/robotology-superbuild/issues/481, we plan to support the compilation of this library on Ubuntu 18.04 at least in the next future. For this reason, this PR fixes the library to compile correctly when on Ubuntu 18.04, that was broken after https://github.com/robotology/yarp-telemetry/pull/132 .
Please squash when merging the PR, thanks!
> Fix compilation when using Ubuntu 18.04 

- src/telemetryDeviceDumper/TelemetryDeviceDumper.cpp
I noticed this log message when using the dumper with the option autosave:
```
acceleration does not contain data, skipping
velocity does not contain data, skipping
encoders does not contain data, skipping
```
By checking the code I noticed that when the `close()` is called, it tries to save data to a file. But in case the option autosave is `true`, data have already been written. I added a statement to check whether the option is true. If yes, the saving is not called.
cc @prashanthr05
> Fix close method of DeviceDumper

- CHANGELOG.md
- README.md
- src/telemetryDeviceDumper/TelemetryDeviceDumper.cpp
- src/telemetryDeviceDumper/TelemetryDeviceDumper.h
- src/telemetryDeviceDumper/app/telemetryDeviceDumper_sim.xml
This PR adds the possibility to log the odometry data.
It fixes #126 
There are still some open points:
- Differently from the other data retrieved through the attaching and the control_board_remapper, for the odometry we used the `localization2DClient`, since the localization device can run on different machines from the `r1-base`, and the localization pipeline has never been used with `yarprobotinterface`. We have to discuss the pro and cons of following this approach or the "attach" approach
- Now we added the log odometry to `logAllQuantities` option, but it may break some existing configurations, since on icub the open of the `localization2DClient` will fail. Maybe we should divide in control board quantities from the rest?
- Until now we always assumed that the remapper should be …
> telemetryDeviceDumper: add log of Odometry

- .github/workflows/conda-ci.yml
The CI has been using the defaults channel (even if this was not wanted) for a long time, see https://github.com/conda-incubator/setup-miniconda/issues/186 . However, since yesterday this created a compilation error:
~~~
2021-07-30T02:25:20.1711320Z /usr/share/miniconda/envs/test/x86_64-conda-linux-gnu/include/c++/9.3.0/ctime:80:11: error: '::timespec_get' has not been declared
2021-07-30T02:25:20.1712202Z    80 |   using ::timespec_get;
2021-07-30T02:25:20.1712597Z       |           ^~~~~~~~~~~~
~~~
For this reason, better to cleanup the use of conda channels in the CI, making sure that we don't use `defaults` at all.
> Fix Conda CI on Linux avoiding to use the defaults channel

- CMakeLists.txt
- README.md
We used to depend to the development branch of `nlohmann_json`, but since a new version has been release (https://github.com/nlohmann/json/releases/tag/v3.10.0) we can use the tag instead.
> Set the required version of nlohmann_json to 3.10.0

- CHANGELOG.md
- src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferManager.h
In the previous implementation, if the path did not exist, the configure failed, I think it is more user friendly if the directory is created.
cc @GiulioRomualdi
> BufferManager: add dir creation

- CHANGELOG.md
- README.md
- src/examples/telemetry_buffer_manager_conf_file.cpp
- src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferConfig.h
- src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferManager.h
With this PR it will be possible to support different methods for file indexing. 
For instance setting
```cpp
config.file_indexing = "%Y_%m_%d_%H_%M_%S";
```
you will get a file named `<file_name>_2021_12_13_19_42_08.mat`
cc @Nicogene @AlexAntn @traversaro @S-Dafarra
> Add the possibility to use a different file indexing for the mat files

- src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferManager.h
I noticed this failure in robotology-superbuild CI (see https://github.com/robotology/robotology-superbuild/actions/runs/1580830893):
~~~
2021-12-15T02:27:00.6953122Z [1/6] Building CXX object src/telemetryDeviceDumper/CMakeFiles/yarp_telemetryDeviceDumper.dir/yarp_plugin_telemetryDeviceDumper.cpp.o
2021-12-15T02:27:00.6954729Z FAILED: src/telemetryDeviceDumper/CMakeFiles/yarp_telemetryDeviceDumper.dir/yarp_plugin_telemetryDeviceDumper.cpp.o 
2021-12-15T02:27:00.6962577Z /usr/bin/c++ -Dyarp_telemetryDeviceDumper_EXPORTS -I/__w/robotology-superbuild/robotology-superbuild/src/YARP_telemetry/src/libYARP_telemetry/src -isystem /__w/robotology-superbuild/robotology-superbuild/build/install/include -Wall -Wextra -Wsign-compare -Wpointer-arith -Winit-self -Wnon-virtual-dtor -Wcast-align -Wunused …
> Add missing iomanip include due to std::put_time use

- CHANGELOG.md
- README.md
- src/examples/conf/test_json.json
- src/examples/telemetry_buffer_manager_conf_file.cpp
- src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferConfig.cpp
- src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferConfig.h
- src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferManager.h
This PR adds the possibility to specify the version of the matfile (see here: https://github.com/ami-iit/matio-cpp/issues/52)
If the user does not specify the version the `default` option is used (as before) 
cc @S-Dafarra @Nicogene @traversaro @AlexAntn
> Add the possibility to specify the saved matfile version

- CHANGELOG.md
- README.md
- src/examples/telemetry_buffer_manager_example.cpp
- src/libYARP_telemetry/src/CMakeLists.txt
- src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferManager.h
- src/libYARP_telemetry/src/yarp/telemetry/experimental/TreeNode.h
- test/BufferManagerTest.cpp
This PR implements a new approach to save data in `yarp-telemetry` library. Before entering into the details I want to underline that:
1. This PR is **back-compatible**. The already existing code that uses yarp telemetry still work and the final user will not see any difference in the mat file used to store the data
2. This PR closes https://github.com/robotology/yarp-telemetry/issues/145
As already explained in https://github.com/robotology/yarp-telemetry/issues/145 one of the main limitations of telemetry is the absence of a multilayer structure to store the data. For instance, it would be nice to have all the measurements of the FT contained in the same Matlab structure. Having this goal in mind we can imagine that a `mat` file is just a `tree` containing several structures where each …
> Add the possibility to have multilayer structures in the BufferManager

- .github/workflows/conda-ci.yml
This CI works with `windows-2019`
> Fix conda CI

- CHANGELOG.md
- CMakeLists.txt
- README.md
- src/examples/conf/test_json.json
- src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferConfig.cpp
- src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferConfig.h
- src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferManager.h
- test/BufferManagerTest.cpp
This PR adds a new entry for each stored variable called `elements_names`. The entry is a cell that will contain the name of each element of a variable. 
BufferInfo is now a struct that contains the `name`, the `dimension`, and the `elements_names`.
cc @traversaro @S-Dafarra @Nicogene @AlexAntn
> Add the possibility to store the elements_names for each channel

- CHANGELOG.md
- src/examples/telemetry_buffer_manager_conf_file.cpp
- src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferConfig.h
- src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferManager.h
I just noticed that since https://github.com/robotology/yarp-telemetry/pull/146, when running the example ``telemetry_buffer_manager_conf_file_example``, we have the following output
```
==13014== 
==13014== HEAP SUMMARY:
==13014==     in use at exit: 0 bytes in 0 blocks
==13014==   total heap usage: 62 allocs, 62 frees, 104,173 bytes allocated
==13014== 
==13014== All heap blocks were freed -- no leaks are possible
==13014== 
==13014== For lists of detected and suppressed errors, rerun with: -s
==13014== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
==13019== Memcheck, a memory error detector
==13019== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==13019== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==13019== Command: …
```
> Fixed bug preventing the save of files when multiple channels are empty.

- CHANGELOG.md
- README.md
- src/examples/telemetry_buffer_manager_conf_file.cpp
- src/examples/telemetry_buffer_manager_example.cpp
- src/examples/telemetry_buffer_periodic_save.cpp
- src/librobometry/CMakeLists.txt
- src/librobometry/include/robometry/BufferManager.h
- src/librobometry/src/BufferManager.cpp
- src/telemetryDeviceDumper/TelemetryDeviceDumper.h
- test/BufferManagerTest.cpp
With this PR I completely removed the use of templates for ``BufferManager`` since the default template was in any case causing issues.
I have also fixed a small discrepancy in the definition of the dimensions of cell and struct arrays.
> Avoid using templates in BufferManager.

- README.md
After https://github.com/conda-forge/staged-recipes/pull/20219, robometry is officially available on conda-forge without the need to use the additional robotology channel.
> Switch README to point to conda-forge package of robometry

- src/telemetryDeviceDumper/TelemetryDeviceDumper.cpp
- src/telemetryDeviceDumper/TelemetryDeviceDumper.h
Before it used only 10 ms as default.
cc @marcoaccame @simeonedussoni
> TelemetryDeviceDumper: add log_period parameter

- README.md
This should fix the number of samples being saved in the snippet examples. All examples, in fact, claim to save 3 samples while all 'for' loops were from 0 to 10.
> Fix number of samples

- README.md
- src/telemetryDeviceDumper/CMakeLists.txt
- src/telemetryDeviceDumper/TelemetryDeviceDumper.cpp
- src/telemetryDeviceDumper/TelemetryDeviceDumper.h
Add to the `telemetryDeviceDumper` a device based on the nwc `rawValuesPublisherClient` thus to save in the MATLAB file generated by this plugin the raw values (and whatever one desired for debugs based on the Interface `iCub::debugLibrary::IRawValuesPublisher`) coming from the boards at the fw level.
**Side Note:** I'll open this PR since I've tested the update done on my bench setup. However, the work, even though at a good point, cannot be considered fully completed. The PR will be kept in draft for now and used for discussion on the updates done and to revise them together
cc: @valegagge @Nicogene @traversaro
> Add to TelemetryDeviceDumper streaming of rawValues from low level

- README.md
- src/telemetryDeviceDumper/TelemetryDeviceDumper.cpp
- src/telemetryDeviceDumper/TelemetryDeviceDumper.h
This PR, which is strictly correlated to the modifications done by @GiulioRomualdi in https://github.com/robotology/yarp/pull/3188 and to the information added in [this issue](https://github.com/icub-tech-iit/five/issues/314), allow to add to the `motor_states` in the `MATLAB` files given by the `TelemetryDeviceDumper` the motor temperatures.
As added with a note in the `README.md`, this is still an unstable feature that for working needs manual changes to the compilation of icub-main.
Thus, I suggest to use it with care and mainly by developers or under their supervision for the initial compilation, since it might lead to compilation issues with icub-main. 
cc: @valegagge
> Add motor temperature streaming in the `TelemetryDeviceDumper` 
